export const FILTER_IMAGES = 'FILTER_IMAGES';


export const LOAD_IMAGES_IN_PROGRESS = 'LOAD_IMAGES_IN_PROGRESS';


export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';


export const LOAD_IMAGES_FAILURE = 'LOAD_IMAGES_FAILURE';

