name: CI and CD
on: [push]
jobs:
  trying-to-use-environment-secrets:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          echo ${{ secrets.VITE_CONTENTFUL_SPACE_ID }}
          echo "DEV_SERVER_URL=${{ secrets.VITE_CONTENTFUL_DELIVERY_API_ACCESS_TOKEN }}"
