name: CI and CD
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          target_branch: gh-pages
          folder: build
        env:
          GITHUB_TOKEN:
            ${{ secrets.UNEVEN_ARTWORK_REACT }}